#!/bin/bash

# The above shebang is just here as a hint for VSCode, etc. in all these files.  Most
# files here are actually intended to work in several shells. (e.g., bash, zsh)

# Dug up on https://unix.stackexchange.com/questions/4965/keep-duplicates-out-of-path-on-source,
# where they were orginally credited to fink; used to provide PATH modification
# idempotence needed to fix VSCode's insistance on using login shells...

append_path() {
    if ! eval test -z "\"\${$1##*:$2:*}\"" -o -z "\"\${$1%%*:$2}\"" -o -z "\"\${$1##$2:*}\"" -o -z "\"\${$1##$2}\"" ; then
        eval "$1=\$$1:$2"
    fi
}

prepend_path() {
    if ! eval test -z "\"\${$1##*:$2:*}\"" -o -z "\"\${$1%%*:$2}\"" -o -z "\"\${$1##$2:*}\"" -o -z "\"\${$1##$2}\"" ; then
        eval "$1=$2:\$$1"
    fi
}

# Courtesy: https://stackoverflow.com/questions/1527049/how-can-i-join-elements-of-an-array-in-bash
join_by() { local IFS="$1"; shift; echo "$*"; }

[[ -d "${HOME}/opt/bin" ]] && prepend_path PATH ${HOME}/opt/bin
[[ -d "${HOME}/bin" ]] && prepend_path PATH ${HOME}/bin
