#!/bin/bash

# Forgot why I needed this, or why I gave it this name, but I'll keep it around as an
# example of using map with jq
az-abn() {
    az account list | jq -r --arg name "$1" 'map(select(.name | test($name; "i"))) | .[].id'
}
