#!/bin/bash

__conda_setup="$('/opt/homebrew/Caskroom/miniforge/base/bin/conda' 'shell.zsh' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "${__conda_setup}"
else
    if [ -f "/opt/homebrew/Caskroom/miniforge/base/etc/profile.d/conda.sh" ]; then
        . "/opt/homebrew/Caskroom/miniforge/base/etc/profile.d/conda.sh"
    else
        export PATH="/opt/homebrew/Caskroom/miniforge/base/bin:${PATH}"
    fi
fi
unset __conda_setup

alias cenv='conda info --json | jq -r ".default_prefix"'
alias cd-cenv='cd $(conda info --json | jq -r ".default_prefix")'

conda-up() {
    for E in $(conda env list|awk 'NR>2{print $1}'); do
        conda update -n ${E} --all -y
    done
}
