#!/bin/bash

set -o vi

HISTCONTROL=ignoreboth
HISTSIZE=10000
HISTFILESIZE=20000

shopt -s histappend
shopt -s checkwinsize

if [ -x $(which dircolors) ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'
    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi

if [ -f /etc/bash_completion ] && ! shopt -oq posix; then
    . /etc/bash_completion
fi

## Not that I use most of these much (or, ever), but it's handy to be able to flip them easily if I do
shopt-alias() {
    for OPT in $(shopt|awk '{print $1}'); do
        # Don't stomp on any existing stuff
        if ! which $OPT && ! alias $OPT 2>/dev/null && ! declare -f $OPT; then
            alias $OPT="if shopt -q $OPT; then shopt -u $OPT && echo \"$OPT off\"; \
                else shopt -s $OPT && echo \"$OPT on\"; fi"
        fi
    done
}
shopt-alias
