#!/bin/bash

function _sh_ps1() {
    # Shamelessly lifted from HypriotOS on my RPi2, who lifted it from:
    #
    # @gf3's Sexy Bash Prompt, inspired by "Extravagant Zsh Prompt"
    # at https://github.com/gf3/dotfiles

    PROMPTCHAR="∴ "

    if [[ $COLORTERM = gnome-* && $TERM = xterm ]] && infocmp gnome-256color >/dev/null 2>&1; then
        export TERM=gnome-256color
    elif infocmp xterm-256color >/dev/null 2>&1; then
        export TERM=xterm-256color
    fi

    if tput setaf 1 &> /dev/null; then
        tput sgr0
        if [[ $(tput colors) -ge 256 ]] 2>/dev/null; then
            BLUE=$(tput setaf 32)
            RED=$(tput setaf 9)
            ORANGE=$(tput setaf 172)
            GREEN=$(tput setaf 70)
            PURPLE=$(tput setaf 141)
        else
            BLUE=$(tput setaf 9)
            RED=$(tput setaf 5)
            ORANGE=$(tput setaf 3)
            GREEN=$(tput setaf 2)
            PURPLE=$(tput setaf 1)

        fi
        BOLD=$(tput bold)
        RESET=$(tput sgr0)
    else
        BLUE="\033[1;34m"
        RED="\033[1;31m"
        ORANGE="\033[1;33m"
        GREEN="\033[1;32m"
        PURPLE="\033[1;35m"
        BOLD=""
        RESET="\033[m"
    fi

    PS1="\n$(usernamehost)\[$GREEN\]\w\$(git_info)\[$RESET\]\n\[$RESET\]${PROMPTCHAR}"
}

function git_info() {
    # check if we're in a git repo
    git rev-parse --is-inside-work-tree &>/dev/null || return

    # quickest check for what branch we're on
    branch=$(git symbolic-ref -q HEAD | sed -e 's|^refs/heads/||')

    # check if it's dirty (via github.com/sindresorhus/pure)
    dirty=$(git diff --quiet --ignore-submodules HEAD &>/dev/null; [ $? -eq 1 ]&& echo -e "*")

    echo ${RESET}" on "${PURPLE}${branch}${dirty}
}

function usernamehost() {
    echo "${BLUE}${CONDA_PROMPT_MODIFIER}${RED}$USER${RESET}@${ORANGE}$HOSTNAME${RESET}:";
}

function _go_ps1() {
    PS1="\n$(~/go/bin/powerline-go \
        -modules venv,user,host,cwd,perms,git,jobs,exit \
        -priority user,host,venv,cwd,git,perms,jobs,exit \
        -colorize-hostname \
        -cwd-mode plain \
        -newline \
        -max-width 80 $?)"
}

# if [ "$TERM" != "linux" -a -x ~/go/bin/powerline-go ]; then
#     PROMPT_COMMAND="_go_ps1; $PROMPT_COMMAND"
# else
#     PROMPT_COMMAND="_sh_ps1; $PROMPT_COMMAND"
# fi

PROMPT_COMMAND="_sh_ps1; $PROMPT_COMMAND"
