#!/usr/bin/env zsh

function powerline_precmd() {
    # eval "$(${HOME}/go/bin/powerline-go -error $? -shell zsh -eval -modules-right git)"
    eval "$(${HOME}/go/bin/powerline-go \
        -shell zsh \
        -error $? \
        -cwd-mode plain \
        -modules kube,venv,user,host,ssh,cwd,perms,git \
        -hostname-only-if-ssh \
        -modules-right exit \
        -eval)"
}

function install_powerline_precmd() {
  for s in "${precmd_functions[@]}"; do
    if [ "$s" = "powerline_precmd" ]; then
      return
    fi
  done
  precmd_functions+=(powerline_precmd)
}

if [ "$TERM" != "linux" ]; then
    install_powerline_precmd
fi
