#!/bin/bash

# [ -x $(which pyenv) ] && \
#     eval "$(pyenv init -)" && \
#     eval "$(pyenv virtualenv-init -)" && \
#     export PYENV_VIRTUALENV_DISABLE_PROMPT=1

# [Originally] Created by miniconda3 20200926 installer
__conda_setup="$(${HOME}/miniconda3/bin/conda shell.$(basename ${SHELL}) hook 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "${__conda_setup}"
else
    if [ -f "${HOME}/miniconda3/etc/profile.d/conda.sh" ]; then
        . "${HOME}/miniconda3/etc/profile.d/conda.sh"
    else
        export PATH="${HOME}/miniconda3/bin:${PATH}"
    fi
fi
unset __conda_setup

alias cenv='conda info --json | jq -r ".default_prefix"'
alias cd-cenv='cd $(conda info --json | jq -r ".default_prefix")'

conda-up() {
    for E in $(conda env list|awk 'NR>2{print $1}'); do
        conda update -n ${E} --all -y
    done
}
