#!/bin/bash

# type jenv $> /dev/null && \
#     eval "$(jenv init -)" && \
#     prepend_path PATH ${HOME}/.jenv/bin

export SDKMAN_DIR="${HOME}/.sdkman"
[[ -s "${HOME}/.sdkman/bin/sdkman-init.sh" ]] && \
    source "${HOME}/.sdkman/bin/sdkman-init.sh"
