#!/bin/bash

whence -w terraform &>/dev/null && {
    alias tf='terraform'
    alias tfv='TF_LOG=INFO terraform'
    alias tfvv='TF_LOG=TRACE terraform'
}
whence -w terragrunt &>/dev/null && alias tg='terragrunt'
